/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Listar_Vehiculos;

import DAOvehiculos.DAOvehiculos;
import Editar_Vehiculo.EditarVehiculo;
import Ingresar_Vehiculo.IngresarVehiculo;
import gestion_parqueadero.VentanaPrincipal;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import vehiculos.VehiculosController;

/**
 *
 * @author PERSONAL
 */
public class VentanaListarVehiculos extends javax.swing.JFrame {
    
    private static VentanaListarVehiculos instancia=null;
    private DefaultTableModel modelo;
   
    /**
     * Creates new form VentanaListarVehiculos
     */
    private VentanaListarVehiculos() {
        initComponents();
    }
    
    private void ActuListaVehiculo (){
     DAOvehiculos vehCont = VehiculosController.getInstance();
     modelo = vehCont.MostrarVehiculos();
      jTable1.setModel (vehCont.MostrarVehiculos());      
    }
    
    public static VentanaListarVehiculos getInstance(){
        if (instancia==null)
            instancia=new VentanaListarVehiculos();
        instancia.ActuListaVehiculo();
        return instancia; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        JPanelBotones = new javax.swing.JPanel();
        BtnRegresar = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();
        BtnRetirarVh = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Listar Vehiculos");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Listar vehiculos estacionados");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono listar vehiculos.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Placa", "N propietario", "Tipo"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        JPanelBotones.setLayout(new java.awt.GridLayout(1, 0));

        BtnRegresar.setText("Regresar");
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });
        JPanelBotones.add(BtnRegresar);

        BtnEditar.setText("Editar");
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });
        JPanelBotones.add(BtnEditar);

        BtnRetirarVh.setText("Retirar Vehiculo");
        BtnRetirarVh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRetirarVhActionPerformed(evt);
            }
        });
        JPanelBotones.add(BtnRetirarVh);

        jButton1.setText("Guardar ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        JPanelBotones.add(jButton1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JPanelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
        // TODO add your handling code here:
        VentanaPrincipal menuInicio= VentanaPrincipal.getInstancia();
        menuInicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnRegresarActionPerformed

    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed
        // TODO add your handling code here:
           try{
            if(jTable1.getSelectedRow()>=0){
                String seleccionTxt=""+modelo.getValueAt(jTable1.getSelectedRow(),jTable1.getSelectedColumn());
              
                //Arreglo de vehiculos
                if(!seleccionTxt.equals("null")){
                    //Arreglo de pokemon
                    String[] vehiculo =new String[3];
                    for(int i=0;i<3;i++){
                        vehiculo[i]=modelo.getValueAt(jTable1.getSelectedRow(),i).toString();
                    }
                    EditarVehiculo editar = EditarVehiculo.getInstance();
                    editar.setVisible(true);
                    editar.porDefecto();
                    editar.datosPorActualizar(vehiculo);
                    this.dispose();                 
                    
                }else{
                    JOptionPane.showMessageDialog(null,"Debe seleccionar un campo no vacio", "Advertencia", JOptionPane.WARNING_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null,"Debe seleccionar un elemento", "Advertencia", JOptionPane.ERROR_MESSAGE);
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.toString());
        }
    }//GEN-LAST:event_BtnEditarActionPerformed

    private void BtnRetirarVhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRetirarVhActionPerformed
        // TODO add your handling code here: 
       try
       {
           VehiculosController vehiculo= VehiculosController.getInstance();
            int seleccion;
        
            seleccion=jTable1.getSelectedRow();
            vehiculo.EliminarVehiculo(seleccion);
            jTable1.setModel(vehiculo.MostrarVehiculos());
       }catch(Exception e)
       {
           JOptionPane.showMessageDialog(null, "selecciona un elemento");
       }
    }//GEN-LAST:event_BtnRetirarVhActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        DAOvehiculos vehCont = VehiculosController.getInstance();
        if(vehCont.GuardarArchivo()){
            JOptionPane.showMessageDialog(null,"Guardado Exitoso");
        }else{
            JOptionPane.showMessageDialog(null,"Error al guardar");
        }
                  
  
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JButton BtnRetirarVh;
    private javax.swing.JPanel JPanelBotones;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}