/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ingresar_Vehiculo;
import DAOvehiculos.DAOvehiculos;
import gestion_parqueadero.VentanaPrincipal;
import javax.swing.JOptionPane;
import vehiculos.VehiculosController;


/**
 *
 * @author Daniel Caceres
 */
public class IngresarVehiculo extends javax.swing.JFrame  {
    
   private static IngresarVehiculo instancia;
   

    /**
     * Creates new form IngresarVehiculo
     */
   
      public static IngresarVehiculo getInstancia() {
       if (instancia == null)
       {
           instancia = new IngresarVehiculo();
        
       }
       return instancia;
   }

   
    private IngresarVehiculo() {
        initComponents();
        
        btnGuadarRegresar.setEnabled(false);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoVehiculos = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        TexFiePlaca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TexFieNombreP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblvali1 = new javax.swing.JLabel();
        lblvali2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Ch_Motocicleta = new javax.swing.JRadioButton();
        Ch_Automovil = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        btnGuadarRegresar = new javax.swing.JButton();
        BtnRegresar = new javax.swing.JButton();
        lblvali3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ingresar Vehiculo");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingreso de nuevo Vehiculo");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/8684388_parking_car_maps_location_placeholder_icon (1).png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion"));

        TexFiePlaca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TexFiePlaca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TexFiePlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TexFiePlacaActionPerformed(evt);
            }
        });
        TexFiePlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TexFiePlacaKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Ingrese la placa del vehiculo ");

        TexFieNombreP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TexFieNombreP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TexFieNombreP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TexFieNombrePActionPerformed(evt);
            }
        });
        TexFieNombreP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TexFieNombrePKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Ingrese Nombre del Propietario");

        lblvali1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblvali1.setForeground(new java.awt.Color(204, 0, 51));

        lblvali2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblvali2.setForeground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(55, 55, 55))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TexFiePlaca, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(lblvali1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TexFieNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblvali2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TexFieNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TexFiePlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblvali1)
                    .addComponent(lblvali2))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Vehiculo"));

        GrupoVehiculos.add(Ch_Motocicleta);
        Ch_Motocicleta.setText("Motocicleta");
        Ch_Motocicleta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Ch_MotocicletaMouseClicked(evt);
            }
        });

        GrupoVehiculos.add(Ch_Automovil);
        Ch_Automovil.setText("Automovil");
        Ch_Automovil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Ch_AutomovilMouseClicked(evt);
            }
        });
        Ch_Automovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ch_AutomovilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(Ch_Motocicleta, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(Ch_Automovil, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ch_Automovil)
                    .addComponent(Ch_Motocicleta))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        btnGuadarRegresar.setText("Guardar y Regresar");
        btnGuadarRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuadarRegresarActionPerformed(evt);
            }
        });

        BtnRegresar.setText("Regresar");
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGuadarRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(BtnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(btnGuadarRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnRegresar))
        );

        lblvali3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblvali3.setForeground(new java.awt.Color(204, 0, 51));
        lblvali3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblvali3, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblvali3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void porDefecto(){
        TexFieNombreP.setText("Nombre");
        TexFiePlaca.setText("Placa");
        Ch_Automovil.setSelected(false);
        Ch_Motocicleta.setSelected(false);
    }
    public void validaCampos (){
        if ( TexFiePlaca.getText().isEmpty()){
            lblvali1.setText("Campo Requerido (*)");
        }else{
            lblvali1.setText(" ");
        }
        if (TexFieNombreP.getText().isEmpty()){
            lblvali2.setText("Campo Requerido (*)");
        }else{
            lblvali2.setText(" ");
        }
        String miTipo = " ";
        if (Ch_Motocicleta.isSelected()|| Ch_Automovil.isSelected()){
            miTipo += "lleno";
            lblvali3.setText(" ");
            
        }else{
            lblvali3.setText("Seleccione uno de los Tipos (*)");
        }
        if (TexFiePlaca.getText().isEmpty()|| TexFieNombreP.getText().isEmpty()|| miTipo.equals(" ")){
            btnGuadarRegresar.setEnabled(false);
        }else{
            btnGuadarRegresar.setEnabled(true);
        }
                
    }
    private void TexFiePlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TexFiePlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TexFiePlacaActionPerformed

    private void TexFieNombrePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TexFieNombrePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TexFieNombrePActionPerformed

    private void Ch_AutomovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ch_AutomovilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ch_AutomovilActionPerformed

    private void btnGuadarRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuadarRegresarActionPerformed
        // TODO add your handling code here:
        DAOvehiculos vehCont = VehiculosController .getInstance();
        String placa = TexFiePlaca.getText();
        String nombrePropietario = TexFieNombreP.getText();
       
        String tipoVehiculo = "";
        if (Ch_Motocicleta.isSelected())
            tipoVehiculo += "Motocicleta";
        
         if (Ch_Automovil.isSelected())
            tipoVehiculo += "Automovil";
        
        String [] vehiculo = {placa,nombrePropietario,tipoVehiculo};
        if (vehCont.GuardarVehiculo(vehiculo))
            
            JOptionPane.showMessageDialog(this, "Vehiculo guardado con exito");
        
        
        
        
        // limpiar los campos de placa, nombre del usuario, y tipo de vehiculo
        
        TexFiePlaca.setText("");
        TexFieNombreP.setText("");
        GrupoVehiculos.clearSelection();
        
        
        VentanaPrincipal menuOne = VentanaPrincipal.getInstancia();
        menuOne.setVisible(true);
        this.dispose();
        
  
    }//GEN-LAST:event_btnGuadarRegresarActionPerformed

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
        // TODO add your handling code here:
        VentanaPrincipal menuOne = VentanaPrincipal.getInstancia();
        menuOne.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnRegresarActionPerformed

    private void TexFiePlacaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TexFiePlacaKeyReleased
        // TODO add your handling code here:
        
        validaCampos();
    }//GEN-LAST:event_TexFiePlacaKeyReleased

    private void TexFieNombrePKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TexFieNombrePKeyReleased
        // TODO add your handling code here:
        
        validaCampos();
    }//GEN-LAST:event_TexFieNombrePKeyReleased

    private void Ch_MotocicletaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ch_MotocicletaMouseClicked
        // TODO add your handling code here:
        
        validaCampos ();
    }//GEN-LAST:event_Ch_MotocicletaMouseClicked

    private void Ch_AutomovilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ch_AutomovilMouseClicked
        // TODO add your handling code here:
        
        validaCampos ();
    }//GEN-LAST:event_Ch_AutomovilMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JRadioButton Ch_Automovil;
    private javax.swing.JRadioButton Ch_Motocicleta;
    private javax.swing.ButtonGroup GrupoVehiculos;
    private javax.swing.JTextField TexFieNombreP;
    private javax.swing.JTextField TexFiePlaca;
    private javax.swing.JButton btnGuadarRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblvali1;
    private javax.swing.JLabel lblvali2;
    private javax.swing.JLabel lblvali3;
    // End of variables declaration//GEN-END:variables
}
